name: Vetclinic GitHub action for docker registry 
on:
  push:
    branches:
      - main

# Env variable
env:
  DOCKER_USER: grupa8180
  DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
  AWS_PRIVATE_KEY: ${{secrets.AWS_EC2_PRIVATE_KEY}}
  REPO_NAME: vetclinicgrupa1
  EC2_PUBLIC_IP: 50.18.36.144
  S3_BUCKET_IMAGE: "grupa8180/petclinic:5.3.22"

jobs:
  build:  
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v4 
    - name: docker login
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Get build hash
      run: echo BUILD_NUMBER=${GITHUB_SHA::7} >> $GITHUB_ENV
    - name: Build the Docker image 
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$BUILD_NUMBER
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:$BUILD_NUMBER
    - name: make tar form image
      run: docker save $DOCKER_USER/$REPO_NAME:$BUILD_NUMBER | gzip > petclinic:5.3.22.tar
    - name: Set up AWS CLI         
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  # Change this to your desired region
    - name: Send Image to S3 bucket
      run: aws s3 cp petclinic:5.3.22.tar s3://grupa1-dev-bucket-s3/images/
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get build hash
      run: echo BUILD_NUMBER=${GITHUB_SHA::7} >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_TOKEN }}
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${EC2_PUBLIC_IP} "sudo docker pull ${DOCKER_USER}/${REPO_NAME}:${BUILD_NUMBER}"
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${EC2_PUBLIC_IP} 'docker stop vetclinicSELFMADE || true'
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${EC2_PUBLIC_IP} 'docker rm vetclinicSELFMADE || true'
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${EC2_PUBLIC_IP} "docker run -d --name vetclinicSELFMADE -p 8080:8080 ${DOCKER_USER}/${REPO_NAME}:${BUILD_NUMBER}"
